apiVersion: v1
kind: Namespace
metadata:
  name: database-exp
  labels:
    name: database-exp
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: demo-cluster
  namespace: database-exp
spec:
  instances: 4

  storage:
    size: 1Gi